### ISSUE TITLE
How chunk are transformed 

### ISSUE THREAD

**Issue by golemax** [tmpim/juroku#6]
How does the algorithm work which transforms a chunk of 2x6 pixels with a palette of 6 colors into a chunk of 2x6 pixels with a palette of 2  colors?

**Comment by 1lann** [comment]
The algorithm is here in `ChunkImage`: https://github.com/tmpim/juroku/blob/master/image.go

Basically it applies a [Sobel filter](https://en.wikipedia.org/wiki/Sobel_operator) which is used as a heuristic to weight colors, and the top 2 weighted colors summed together in a 2x6 grid are chosen. 

The Sobel filter weighs pixels that have more contrast relative to their surrounding pixels, which gives Juroku images sharper edges and more readable text.

**Comment by therollingkitten** [comment]
thank you for your explanation
